version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: '08:00'
    timezone: America/New_York
  open-pull-requests-limit: 10
  reviewers:
  - jakepurple13
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - ">= 4.1.a, < 4.2"
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - "> 4.7.0, < 4.8"
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-android
    versions:
    - "> 1.3.5, < 2"
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - "> 1.3.5, < 2"
